<a href="https://colab.research.google.com/github/OswaldMG/Comprobacion-Matrices/blob/main/ComprobacionMatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prueba de funcionamiento

In [ ]:
# prompt: necesito un codigo que haga todas las operaciones posibles en python con matrices

import numpy as np

def matrix_operations(matrix1, matrix2):
  """
  Realiza varias operaciones con matrices.

  Args:
    matrix1: La primera matriz (NumPy array).
    matrix2: La segunda matriz (NumPy array).

  Returns:
    Un diccionario que contiene los resultados de las operaciones.
    Devuelve un mensaje de error si las matrices no son compatibles.
  """

  results = {}

  try:
    # Suma
    results['suma'] = matrix1 + matrix2

    # Resta
    results['resta'] = matrix1 - matrix2

    # Multiplicación matriz a elemento
    results['multiplicacion_matriz_a_elemento'] = matrix1 * 5

    # Multiplicación matricial
    results['multiplicacion_matricial'] = np.dot(matrix1, matrix2)

    # División matriz a elemento
    results['division_matriz_a_elemento'] = matrix1 / 2


    # Transpuesta de la primera matriz
    results['transpuesta_matrix1'] = matrix1.transpose()

    # Determinante de la primera matriz (si es cuadrada)
    if matrix1.shape[0] == matrix1.shape[1]:
      results['determinante_matrix1'] = np.linalg.det(matrix1)
    else:
      results['determinante_matrix1'] = "La matriz no es cuadrada"

    # Inversa de la primera matriz (si es cuadrada y no singular)
    if matrix1.shape[0] == matrix1.shape[1]:
      try:
          results['inversa_matrix1'] = np.linalg.inv(matrix1)
      except np.linalg.LinAlgError:
          results['inversa_matrix1'] = "La matriz no es invertible"
    else:
      results['inversa_matrix1'] = "La matriz no es cuadrada"

  except ValueError as e:
      return f"Error: {e}. Las matrices no son compatibles para algunas operaciones."

  return results



# Ejemplo de uso:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

resultados = matrix_operations(matrix_a, matrix_b)

for operacion, resultado in resultados.items():
  print(f"{operacion.capitalize()}:")
  print(resultado)
  print("-" * 20)


Suma:
[[ 6  8]
 [10 12]]
--------------------
Resta:
[[-4 -4]
 [-4 -4]]
--------------------
Multiplicacion_matriz_a_elemento:
[[ 5 10]
 [15 20]]
--------------------
Multiplicacion_matricial:
[[19 22]
 [43 50]]
--------------------
Division_matriz_a_elemento:
[[0.5 1. ]
 [1.5 2. ]]
--------------------
Transpuesta_matrix1:
[[1 3]
 [2 4]]
--------------------
Determinante_matrix1:
-2.0000000000000004
--------------------
Inversa_matrix1:
[[-2.   1. ]
 [ 1.5 -0.5]]
--------------------


# **ACT #1**

In [ ]:
import numpy as np

#Matrices
matrix1 = np.array([[5, 2, -4], [6, 0, -3], [7, -1, 2]])
matrix2 = np.array([[1],[1],[2]])

matrix3 = np.array([[5, 3], [4, 6]])
matrix4 = np.array([[5],[7]])

#Operaciones
resultados=np.dot(matrix1, matrix2)
print("Act #1")
print("a)\n",resultados)
resultados=np.dot(matrix3, matrix4)
print("\nb)\n",resultados)
print("-" * 20)


Act #1
a)
 [[-1]
 [ 0]
 [10]]

b)
 [[46]
 [62]]
--------------------


# **Act #2**

In [ ]:
import numpy as np

#Matrices
matrix1 = np.array([[5, 2], [3, 1]])

matrix2 = np.array([[1, 2, 3], [4, 0, -1], [5, 0, 6]])
matrix3 = np.array([[6, 8, 7], [5, -1, 2], [-4, 5, 4]])

matrix4 = np.array([[4, 3], [2, 1]])
matrix5 = np.array([[-1, 2],[1, 0]])

#Operaciones
print("Act #2")
resultados=matrix1*(-6)
print("a)\n",resultados)
resultados=matrix2+matrix3
print("b)\n",resultados)
resultados=(matrix4*5)+(matrix5*6)
print("c)\n",resultados)
print("-" * 20)

Act #2
a)
 [[-30 -12]
 [-18  -6]]
b)
 [[ 7 10 10]
 [ 9 -1  1]
 [ 1  5 10]]
c)
 [[14 27]
 [16  5]]
--------------------


# **Act #4**

In [ ]:
import numpy as np

#Matrices
Ma = np.array([[-1, 0, 2], [5, 6, 1], [0, 0, 2]])
Mb = np.array([[2, 5, 0], [-1, -1, -1], [3, 2, 1]])
Vv = np.array([[1], [0], [2]])
Vw = np.array([[3], [-2], [1]])



#Operaciones
print("Act #4")
resultados=(Ma+Mb).transpose()
resultados=np.dot(resultados,Vv)
print("1)\n",resultados)
resultados=Ma.transpose()
print("2)\n",resultados)
resultados=Mb.transpose()
print("\n",resultados)
resultados=(np.dot(Ma,Vw).transpose())
resultados=np.dot(resultados,np.dot(Mb,Vv))
print("3)\n",resultados)
resultados=np.dot(Ma,Mb)
resultados=resultados.transpose()
print("4)\n",resultados)
resultados=Ma.transpose()
resultados=np.dot(resultados,Mb)
resultados=np.dot(resultados,Vv)
Vw=Vw.transpose()
resultados=np.dot(resultados,Vw)
print("5)\n",resultados)
print("-" * 20)

Act #4
1)
 [[7]
 [9]
 [8]]
2)
 [[-1  5  0]
 [ 0  6  0]
 [ 2  1  2]]

 [[ 2 -1  3]
 [ 5 -1  2]
 [ 0 -1  1]]
3)
 [[-4]]
4)
 [[ 4  7  6]
 [-1 21  4]
 [ 2 -5  2]]
5)
 [[-51  34 -17]
 [-54  36 -18]
 [ 33 -22  11]]
--------------------


# **Act #5**



In [ ]:
import numpy as np

#Matrices
matrix1 = np.array([[0, 1], [1, 0]])
matrix2 = np.array([[3, 4], [2, 1]])
matrix3 = np.array([[1, -4], [-2, 3]])



#Operaciones
print("Act #5")
resultado=np.linalg.inv(matrix1)
print("1)\n",resultados)
resultados=np.linalg.inv(matrix2)
print("2)\n",resultados)
resultados=np.linalg.inv(matrix3)
print("3)\n",resultados)
print("-" * 20)

# **Act #6**

In [ ]:
import numpy as np

#Matrices
matrix1 = np.array([[2, 1], [5, 2]])

matrix2 = np.array([[2, 0], [1, 3]])
matrix3 = np.array([[1, 1], [2, 0]])

matrix4 = np.array([[1/2, -1], [1/4, 2]])
matrix5 = np.array([[2],[4]])

matrix6 = np.array([[1/3, 2/3], [-1, 0]])

matrix7 = np.array([[3, -1]])
matrix8 = np.array([[2/3, 4/3],[1, 6]])
matrix9 = np.array([[1],[1]])

matrix10 = np.array([[5],[0]])
matrix11 = np.array([[2, 8],[-1, 16]])
matrix12 = np.array([[2],[1]])

matrix13 = np.array([[2, 3],[0, 1]])
matrix14 = np.array([[1, 1],[2, 0]])

#Operaciones
print("Act #6")

resultados=np.linalg.inv(matrix1)
print("1)\n",resultados)

matrix2=matrix2.transpose()
matrix3=np.linalg.inv(matrix3)
resultados=np.dot(matrix2,matrix3)
print("2)\n",resultados)

resultados=np.dot(matrix4,matrix5)
print("3)\n",resultados)

resultados=np.linalg.inv(matrix6.transpose())
print("4)\n",resultados)

matrix8=np.linalg.inv(matrix8)
resultados=np.dot(matrix7,matrix8)
resultados=np.dot(resultados,matrix9)
print("5)\n",resultados)

matrix10=matrix10.transpose()
matrix11=np.linalg.inv(matrix11)
resultados=np.dot(matrix10,matrix11)
resultados=np.dot(resultados,matrix12)
print("6)\n",resultados)

resutados=np.dot(matrix13,matrix14)
resultados=np.linalg.inv(resutados)
print("7)\n",resultados)

print("-" * 20)

Act #6
1)
 [[-2.  1.]
 [ 5. -2.]]
2)
 [[ 1.   0.5]
 [ 3.  -1.5]]
3)
 [[-3. ]
 [ 8.5]]
4)
 [[ 0.   1.5]
 [-1.   0.5]]
5)
 [[5.375]]
6)
 [[3.]]
--------------------


# **Act #7**

In [ ]:
import numpy as np

#Matrices
matrix1 = np.array([[1, 0, 0], [2, 1, 0], [4, 4, 4]])
matrix2 = np.array([[-2, 1, 0], [2, 4, 6], [0, 2, 2]])
matrix3 = np.array([[5, 1, 2], [3, 1, 2], [1, 1, 2]])


#Operaciones
print("Act #2")
resultados=np.linalg.inv(matrix1)
print("a)\n",resultados)
resultados=np.linalg.inv(matrix2)
print("b)\n",resultados)
#resultados=np.linalg.inv(matrix3)
#NO se puede, imposible facturar
print("c)\n NO se puede, imposible facturar")
print("-" * 20)

Act #2
a)
 [[ 1.    0.    0.  ]
 [-2.    1.   -0.  ]
 [ 1.   -1.    0.25]]
b)
 [[-1.  -0.5  1.5]
 [-1.  -1.   3. ]
 [ 1.   1.  -2.5]]
c)
 NO se puede, imposible facturar
--------------------


# **Act #8**

In [13]:
import numpy as np

print("Act #8")
print("En un examen de matemáticasde 3 preguntas un estudiante obtuvo una calificación de 7.2. \nLa puntuación del primer problema fue de 40% mas que lo del segundo.\n La del tercero fue del doble de la suma del primero y el segundo")
print("X + Y + Z = 7.2")
print("X - 1.4 = 0")
print("2X + 2Y - Z = 0\n")

#Matrices
matrix=([[1,1,1],[1,-1.4,0],[2,2,-1]])
resultado=([[7.2],[0],[0]])

#Operaciones
inv=np.linalg.inv(matrix)
final=np.dot(inv,resultado)
print(final,"\n")

print("Un estudiante pidió en la cafetería 3 bocadillos, 2 refrescos y 2 bolsas de papas\n")
print("Pagó un total de $19. Al mirar la cuenta comprobó que le habían\ncobrando 1 bocadillo y 1 bolsa de mas. Reclamó y le devolvieron $4.\nPara compensar el error el vendedor le ofreció")
print("llevarse un bocadillo y un refresco por solo $3, lo que suponia un descuento de 40% respecto a los originales. ?Cuáles eran los precios sin descuento?")
print("4X + 2Y + 3Z = 19")
print("X - Z = 4")
print("0.6X + 0.6Y = 3\n")

#Matrices
matrix=([[4,2,3],[1,0,-1],[0.6,0.6,0]])
resultado=([[19],[4],[3]])

#Operaciones
inv=np.linalg.inv(matrix)
final=np.dot(inv,resultado)
print(final,"\n")


print("-" * 20)


0.6X + 0.5Y + 0 = 0.3(X+Y+Z)
0.2X + 0.6Y + 0.6Z = 0.5(X+Y+Z)
X - 2Y = 100

[[-500.]
 [-600.]
 [-900.]] 

En un examen de matemáticasde 3 preguntas un estudiante obtuvo una calificación de 7.2. 
La puntuación del primer problema fue de 40% mas que lo del segundo.
 La del tercero fue del doble de la suma del primero y el segundo
X + Y + Z = 7.2
X - 1.4 = 0
2X + 2Y - Z = 0

[[1.4]
 [1. ]
 [4.8]] 

Un estudiante pidió en la cafetería 3 bocadillos, 2 refrescos y 2 bolsas de papas

Pagó un total de $19. Al mirar la cuenta comprobó que le habían
cobrando 1 bocadillo y 1 bolsa de mas. Reclamó y le devolvieron $4.
Para compensar el error el vendedor le ofreció
llevarse un bocadillo y un refresco por solo $3, lo que suponia un descuento de 40% respecto a los originales. ?Cuáles eran los precios sin descuento?
4X + 2Y + 3Z = 19
X - Z = 4
0.6X + 0.6Y = 3

[[4.2]
 [0.8]
 [0.2]] 

--------------------


# **Act #9**

In [14]:
import numpy as np

print("Act #9")
print("Una marca de vehiculos vende coches blancos, negros y rojos.\n")
print("El 60% de los coches blancos más el 50% de los negros representan el 30% de los coches vendidos")
print("0.6X + 0.5Y + 0 = 0.3(X+Y+Z)")
print("0.2X + 0.6Y + 0.6Z = 0.5(X+Y+Z)")
print("X - 2Y = 100\n")

#Matrices
matrix=([[0.3,0.2,-0.3],[-0.3,0.1,0.1],[1,-1,0]])
resultado=([[0],[0],[100]])

#Operaciones
inv=np.linalg.inv(matrix)
final=np.dot(inv,resultado)
print(final,"\n")

Una marca de vehiculos vende coches blancos, negros y rojos.

El 60% de los coches blancos más el 50% de los negros representan el 30% de los coches vendidos
0.6X + 0.5Y + 0 = 0.3(X+Y+Z)
0.2X + 0.6Y + 0.6Z = 0.5(X+Y+Z)
X - 2Y = 100

[[-500.]
 [-600.]
 [-900.]] 



# **Act #10**

In [29]:
import numpy as np

#Matrices
matrix1=np.array([[2,3],[5,4]])
matrix2=np.array([[-1,0],[0,-1]])

matrix3=np.array([[2,3],[4,0]])
matrix4=np.array([[1,1],[1,-1]])

matrix5=np.array([[2,1,5],[3,1,0],[2,0,1]])
matrix6=np.array([[2,0,0],[0,4,0],[0,0,1]])

matrix7=np.array([[3,-1,2],[2,2,1],[1,1,1]])
matrix8=np.array([[2,0,0],[1,1,1],[2,0,3]])

#Operaciones
print("Act #10")
resultados=np.dot(matrix1,matrix2)
resultados=np.linalg.det(resultados)
print("1)\n",resultados)
matrix3=matrix3 * 2
matrix4=matrix4 * 4
resultados=matrix3 - matrix4
resultados=np.linalg.det(resultados)
print("2)\n",resultados)
resultados=np.dot(matrix5,matrix6)
resultados=np.linalg.det(resultados)
print("3)\n",resultados)
matrix8=np.linalg.inv(matrix8)
resultados=np.dot(matrix7,matrix8)
resultados=np.linalg.det(resultados)
print("4)\n",resultados)

Act #10
1)
 -6.999999999999999
2)
 -7.999999999999998
3)
 -88.00000000000003
4)
 0.6666666666666666


In [ ]:
import numpy as np

M = np.array([[1, 0], [1, 5],[1, 15]])
T = np.array([[0.7],[11.1],[31.2]])

#Operaciones
ctrl=np.dot((M.transpose()),M)
ctrl=np.linalg.inv(ctrl)
ctrl=np.dot(ctrl,M.transpose())
ctrl=np.dot(ctrl,T)
up=ctrl[0]*1
down=ctrl[1]*3
ctrl=up+down
print(ctrl)


[6.89]
